In [1]:
!pip install --upgrade pyswarm
!pip install pymc3
!pip install --upgrade pactools

  Created wheel for pyswarm: filename=pyswarm-0.6-cp36-none-any.whl size=4481 sha256=12582e977d0748250791d261473eb8d333b83979e533d82d67818ff730190eb7
  Stored in directory: /root/.cache/pip/wheels/37/c5/f6/b33b9ac00040cb95c1f00af982a4197334a672d6de43f4699f
Successfully built pyswarm
     |████████████████████████████████| 92kB 2.4MB/s 


In [2]:
from sklearn.model_selection import train_test_split
from pyswarm import pso
from os import path
import os
import requests
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import numpy
import sys
import numpy as np
from numpy import loadtxt
from numpy import array
from numpy.random import choice
import pandas as pd
import time
import random
import statistics
import pandas
import math
import csv
import random
import logging
from pymc3 import *
import pymc3 as pm
from functools import reduce
from operator import add
from tqdm import tqdm
import geopy.distance
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from theano import shared
from sklearn import preprocessing
print('Running on PyMC3 v{}'.format(pm.__version__))
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow
from tensorflow.keras import datasets, layers, models
from keras.utils import np_utils
from keras.utils import to_categorical

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.ticker import MaxNLocator

#TESNORFOW
import tensorflow as tf
from tensorflow import keras
from keras import datasets, layers, models

#KERAS LIBRARIES
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout , Flatten,BatchNormalization,Conv2D,MaxPooling2D, Activation,LSTM,Embedding,Input,GlobalAveragePooling2D
from keras.regularizers import l1, l2, l1_l2
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import backend 
from keras.utils import np_utils
from keras.utils import to_categorical

from numpy import savetxt

from sklearn.metrics import classification_report
from sklearn import preprocessing
import skimage.transform
from sklearn.metrics import confusion_matrix

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Running on PyMC3 v3.7


In [3]:
def data():
  test = np.load('/content/drive/My Drive/NumpyArrayCovidx/test.npy',allow_pickle=True)
  test_labels = np.load('/content/drive/My Drive/NumpyArrayCovidx/test_labels.npy',allow_pickle=True)
  
  test64=test/225.0

  test_mid=np.empty([1785,72,72,3], dtype=int)
  
  for i in range(len(test)):
    test_mid[i] = skimage.transform.resize(test[i], (72, 72))
  
  test72=test_mid/225.0

  return test64,test72,test_labels

In [4]:
test64,test72,test_labels=data()

In [5]:
le = preprocessing.LabelEncoder()
labels = le.fit_transform(test_labels)

In [6]:
target_names = ['covid19', 'normal', 'pneumonia']

In [7]:
pso_vgg = keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_vgg/top-0.928-0.2')
pso_vgg_lstm =  keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_vgg_lstm/top-0.925-0.207')
pso_vgg_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_vgg/top-0.899-0.333')
pso_vgg_lstm_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_vgg_lstm/top-0.908-0.25')

pso_resnet = keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_resnet/top-0.905-0.608')
pso_resnet_lstm =  keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_resnet_lstm/top-0.918-0.48')
pso_resnet_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_resnet/top-0.88-0.854')
pso_resnet_lstm_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_resnet_lstm/top-0.896-0.739')

pso_xception = keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_xception/top-0.93-0.685')
pso_xcpetion_lstm =  keras.models.load_model('/content/drive/My Drive/saved_models/enhanced/pso_xception_lstm/top-0.923-0.476')
pso_xception_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_xception/top-0.894-0.662')
pso_xception_lstm_simple =  keras.models.load_model('/content/drive/My Drive/saved_models/simple/pso_vgg_lstm/top-0.908-0.25')

In [8]:
pred_pso_vgg=pso_vgg.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_vgg)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_vgg,target_names=target_names))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[0.6625     0.93922652 0.88375   ]
              precision    recall  f1-score   support

     covid19       0.83      0.66      0.74        80
      normal       0.89      0.94      0.92       905
   pneumonia       0.92      0.88      0.90       800

    accuracy                           0.90      1785
   macro avg       0.88      0.83      0.85      1785
weighted avg       0.90      0.90      0.90      1785



In [9]:
pred_pso_vgg_lstm=pso_vgg_lstm.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_vgg_lstm)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_vgg_lstm,target_names=target_names))

[0.7        0.94033149 0.8825    ]
              precision    recall  f1-score   support

     covid19       0.67      0.70      0.69        80
      normal       0.91      0.94      0.92       905
   pneumonia       0.92      0.88      0.90       800

    accuracy                           0.90      1785
   macro avg       0.84      0.84      0.84      1785
weighted avg       0.90      0.90      0.90      1785



In [10]:
pred_pso_vgg_simple=pso_vgg_simple.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_vgg_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_vgg_simple,target_names=target_names))

[0.5375     0.93922652 0.90125   ]
              precision    recall  f1-score   support

     covid19       0.90      0.54      0.67        80
      normal       0.90      0.94      0.92       905
   pneumonia       0.91      0.90      0.90       800

    accuracy                           0.90      1785
   macro avg       0.90      0.79      0.83      1785
weighted avg       0.90      0.90      0.90      1785



In [11]:
pred_pso_vgg_lstm_simple=pso_vgg.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_vgg_lstm_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_vgg_lstm_simple,target_names=target_names))

[0.6625     0.93922652 0.88375   ]
              precision    recall  f1-score   support

     covid19       0.83      0.66      0.74        80
      normal       0.89      0.94      0.92       905
   pneumonia       0.92      0.88      0.90       800

    accuracy                           0.90      1785
   macro avg       0.88      0.83      0.85      1785
weighted avg       0.90      0.90      0.90      1785



In [12]:
pred_pso_resnet=pso_resnet.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_resnet)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_resnet,target_names=target_names))

[0.625      0.89281768 0.8825    ]
              precision    recall  f1-score   support

     covid19       0.71      0.62      0.67        80
      normal       0.90      0.89      0.89       905
   pneumonia       0.87      0.88      0.88       800

    accuracy                           0.88      1785
   macro avg       0.83      0.80      0.81      1785
weighted avg       0.88      0.88      0.88      1785



In [13]:
pred_pso_resnet_lstm=pso_resnet_lstm.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_resnet_lstm)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_resnet_lstm,target_names=target_names))

[0.6875     0.90165746 0.89      ]
              precision    recall  f1-score   support

     covid19       0.80      0.69      0.74        80
      normal       0.90      0.90      0.90       905
   pneumonia       0.88      0.89      0.89       800

    accuracy                           0.89      1785
   macro avg       0.86      0.83      0.84      1785
weighted avg       0.89      0.89      0.89      1785



In [14]:
pred_pso_resnet_simple=pso_resnet_simple.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_resnet_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_resnet_simple,target_names=target_names))

[0.575     0.9038674 0.865    ]
              precision    recall  f1-score   support

     covid19       0.85      0.57      0.69        80
      normal       0.88      0.90      0.89       905
   pneumonia       0.86      0.86      0.86       800

    accuracy                           0.87      1785
   macro avg       0.87      0.78      0.81      1785
weighted avg       0.87      0.87      0.87      1785



In [15]:
pred_pso_resnet_lstm_simple=pso_resnet_lstm_simple.predict_classes(test64)
cm = confusion_matrix(labels, pred_pso_resnet_lstm_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_resnet_lstm_simple,target_names=target_names))

[0.6375     0.94143646 0.8525    ]
              precision    recall  f1-score   support

     covid19       0.84      0.64      0.72        80
      normal       0.87      0.94      0.91       905
   pneumonia       0.91      0.85      0.88       800

    accuracy                           0.89      1785
   macro avg       0.87      0.81      0.84      1785
weighted avg       0.89      0.89      0.89      1785



In [16]:
pred_pso_xception=pso_xception.predict_classes(test72)
cm = confusion_matrix(labels, pred_pso_xception)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_xception,target_names=target_names))

[0. 0. 1.]
              precision    recall  f1-score   support

     covid19       0.00      0.00      0.00        80
      normal       0.00      0.00      0.00       905
   pneumonia       0.45      1.00      0.62       800

    accuracy                           0.45      1785
   macro avg       0.15      0.33      0.21      1785
weighted avg       0.20      0.45      0.28      1785



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
pred_pso_xception_lstm=pso_xcpetion_lstm.predict_classes(test72)
cm = confusion_matrix(labels, pred_pso_xception_lstm)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_xception_lstm,target_names=target_names))

[0. 0. 1.]
              precision    recall  f1-score   support

     covid19       0.00      0.00      0.00        80
      normal       0.00      0.00      0.00       905
   pneumonia       0.45      1.00      0.62       800

    accuracy                           0.45      1785
   macro avg       0.15      0.33      0.21      1785
weighted avg       0.20      0.45      0.28      1785



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
pred_pso_xception_simple=pso_xception_simple.predict_classes(test72)
cm = confusion_matrix(labels, pred_pso_xception_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(labels, pred_pso_xception_simple,target_names=target_names))

[0. 0. 1.]
              precision    recall  f1-score   support

     covid19       0.00      0.00      0.00        80
      normal       0.00      0.00      0.00       905
   pneumonia       0.45      1.00      0.62       800

    accuracy                           0.45      1785
   macro avg       0.15      0.33      0.21      1785
weighted avg       0.20      0.45      0.28      1785



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
pred_pso_xception_lstm_simple=pso_xception_lstm_simple.predict_classes(test72)
cm = confusion_matrix(labels, pred_pso_xception_lstm_simple)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())

print(classification_report(labels, pred_pso_xception_lstm_simple,target_names=target_names))

[0. 0. 1.]
              precision    recall  f1-score   support

     covid19       0.00      0.00      0.00        80
      normal       0.00      0.00      0.00       905
   pneumonia       0.45      1.00      0.62       800

    accuracy                           0.45      1785
   macro avg       0.15      0.33      0.21      1785
weighted avg       0.20      0.45      0.28      1785



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
